### PR TITLE
feat: Allow providing `-password` or `-password-hash` via CLI arguments

### PR DESCRIPTION
**Pull request by g3n35i5**
# Usage

**With the `-password` flag**

```console
# docker run --rm -v portainer_data:/data portainer/helper-reset-password:linux-amd64 -password superpassword

{"level":"info","filename":"portainer.db","time":"2023-12-04T12:47:06Z","message":"loading PortainerDB"}
2023/12/04 12:47:06 Using password provided via CLI
2023/12/04 12:47:06 Password successfully updated for user: admin
2023/12/04 12:47:06 Use the following password to login: superpassword
```

**With the `-password-hash` flag**

```console
# docker run --rm httpd:2.4-alpine htpasswd -nbB admin superpassword | cut -d ":" -f 2 | sed 's/\$/\\\$/g'

\$2y\$05\$pcm5aPTy2MSAEXdLxDjx0e8FssOexspSuvZZ2kUce5OLhDMdxerz6

# docker run --rm -v portainer_data:/data portainer/helper-reset-password:linux-amd64 -password-hash \$2y\$05\$pcm5aPTy2MSAEXdLxDjx0e8FssOexspSuvZZ2kUce5OLhDMdxerz6

{"level":"info","filename":"portainer.db","time":"2023-12-04T12:48:44Z","message":"loading PortainerDB"}
2023/12/04 12:48:44 Using password hash provided via CLI
2023/12/04 12:48:44 Password successfully updated for user: admin
2023/12/04 12:48:44 Use the password from your provided hash to login
```

**With both flags**
```console
# docker run --rm -v portainer_data:/data portainer/helper-reset-password:linux-amd64 -password-hash \$2y\$05\$pcm5aPTy2MSAEXdLxDjx0e8FssOexspSuvZZ2kUce5OLhDMdxerz6 -password superpassword

2023/12/04 12:49:16 Invalid CLI usage! err: You cannot use the 'password' and 'password-hash' arguments at the same time
```

**Without any flags**
```console
# docker run --rm -v portainer_data:/data portainer/helper-reset-password:linux-amd64

{"level":"info","filename":"portainer.db","time":"2023-12-04T12:49:50Z","message":"loading PortainerDB"}                                              
2023/12/04 12:49:50 Password successfully updated for user: admin
2023/12/04 12:49:50 Use the following password to login: D3S6_=ov8~`Tl%E0-MJYi$415^2VXKAd
```

### CODE REVIEW

**Comment by g3n35i5** [comment]
@prabhat-org pinging you since you're the last contributor. I would be very happy if my features would be accepted. If there are any requests for changes, I will be happy to add them!

**Comment by prabhat-org** [comment]
@g3n35i5 thanks for your contribution. Just wanted to know the reasoning behind the `password-hash` argument.

**Comment by g3n35i5** [comment]
@prabhat-org I'm using the `-password-hash` CLI argument for an unattended/headless installation with ansible. My problem was that I can start portainer with the `--admin-password` [CLI flag](https://gist.github.com/deviantony/62c009b41bde5e078b1a7de9f11f5e55), but in order to configure portainer via API, I need the password. Thus, I'm generating a random password for the installation and after that, I use the `helper-reset-password` docker image to reset the password to the desired one.

**Comment by g3n35i5** [comment]
@prabhat-org ping?

**Comment by g3n35i5** [comment]
@prabhat-org @stevensbkang @yi-portainer I don't want to be intrusive, but I would be happy if the PR would be merged and a new version would be published, because I can really use this feature. If you have any questions or requests for changes, please do not hesitate to contact me :blush:

**Comment by g3n35i5** [comment]
@stevensbkang @prabhat-portainer @yi-portainer @dakota-portainer sorry for pinging you all but I really want this PR to be merged :see_no_evil: Is this repository still maintained?

**Comment by prabhat83** [comment]
@g3n35i5 Sorry for not replying before. Let me discuss this and will come back to you.

**Review by prabhat83 — APPROVED** [review]

**Comment by prabhat83** [comment]
@g3n35i5 we have merged this PR and generated a new image. Sorry for taking so long.

**Comment by g3n35i5** [comment]
@prabhat-portainer thanks a lot, I'll check whether the new image works :)

**Pull request merged**
